### ISSUE TITLE
[Bug]: Attribute buttons are inactive for all observations

### ISSUE THREAD

**Issue by christillman** [christillman/encounterpro_os#10]
### What happened?

See attached email below. The attribute buttons do not open the expected window.

### How did it happen?

See attached email. It takes you through the screens to replicate the problem.

Hi Chris,

After making upgrades to the client application, some fields (specific result) and (2nd specific result) in the observation (attributes) page were deactivated, but need to be activated for proper setup of client observation fields.

I noticed this I think more than a year ago, but didn't bring it up because we had more pressing issues to work on, and also because I knew that to demonstrate this well, I needed to refer to the legacy application, which I didn't have access to.

Since I am setting up for Livingstone, I have found that these fields need to be reactivated to allow proper setup of several observation fields.

I downloaded the legacy application for comparison purposes, so will be using screenshots from the legacy application to show which fields are inactivated in the current 7.2.1 version.

The steps to access this page is the same for both versions 6.1.1 and version 7.2.1.

Please see below:

1. From the main office page, select the 'Configuration' tab located on the right hand column.

![image](https://github.com/christillman/encounterpro_os/assets/25717203/55b3f5c7-9e38-4fb4-a6aa-98ceba619196)

2. On the configuration page , select the 'Observations' button

![image](https://github.com/christillman/encounterpro_os/assets/25717203/233131f2-749a-45d6-af5b-18a757f8b43c)

3. The observations page will show as seen below. Scroll down and select the 'Vital Signs' button.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/8483a521-175c-4175-9a1e-ffeec07319aa)

3. The observation page listing a few sets of vital signs observations on the left side of the page, will show as seen below. Yours could be more or less.

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/437ab55d-3f72-4920-9625-2f6010fffba3)

If you see no 'Vital Signs' set, you could search for them by selecting the 'Treatment Type' button, on the upper right side of the page, below 'Specialty' button. See below

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/8bc75c7a-091c-40e0-ab6c-6bfbed1fb124)

From the drop down menu, select 'Vital Signs' button.

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/0325fa2f-2d12-454c-b25f-6f8544998388)

A few vital signs sets will show on the left side of the page, as seen below. Select the 'Child CC and Vitals' set.

If it doesnt show on your shortlist, you can search for it by selecting the 'Description' button, located under 'Search Options' heading on the right side of your observations page.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/08623801-5f04-4389-bfd4-38626f7936c9)

In the search field, type  'Child CC' and select the 'OK' button.

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/6c9c7ea6-c6a3-4623-862e-d232f16fc064)

 or select any set of vitals that show up on your short list.

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/90c1af2c-65b3-43c6-9820-5223c242b6fe)

Select the icon (thermometer icon) located on the left side of the  'Child CC and Vitals' bar or your set of vital signs of your choice .

A menu will show as seen below.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/df7300de-9bfa-4416-924e-ede03b3baa6b)

From the menu as seen above, select the 'Edit Observation' button.

A configuration page for the 'Child CC and Vitals' page will show as seen below.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/25362d97-3637-4667-a922-71337155812e)

Select any one of the observations listed under the heading 'Constituent Observations', In my case, I selected 'Weight' observation. See below
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/19d790bb-d98c-4897-940d-27f0431089cc)

From the menu that shows, select the 'Attributes' button.

A page that shows the attributes for the observation will show. In my case, the page will show 'attributes' for the 'Weight' observation I selected. See below.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/97a0bf78-53c9-40fb-9b0e-d57bf18714ec)

On this attributes page, the 'Specific Result', and '2nd Specific Result' fields for all observations have been inactivated in EPRO version 7.2.1.

In the legacy application, when I select the 'Specific Result' field, it opens a small window which is what allows one to determine how to display the result.

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/afc1a2f2-84a3-4768-a637-9e1a1e088288)

If I select the '2nd Specific Result' field, it also opens a window allowing one to choose how to display the result.

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/2abf30f5-9206-4f29-8015-b4930a92b55b)

Both of these fields are inactivated in version 7.2.1 for all observations.

Could they please be reactivated?

### Expectations

See attached email above. It shows it worked in an earlier version.

### Urgency and Importance

I am trying to set up for a new customer, so the problem is urgent.

### Version

7.2.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christillman** [comment]
Please verify the problem is fixed in 7.2.1.1,

**Comment by MCIR** [comment]
the issue has been resolved in the specific area where the issue was identified. I need to test in other areas in the application to ensure attribute buttons for different types of observations are active.
