### ISSUE TITLE
Suppress the 'Dose Based on field' that shows when drug prescription page is accessed from certain access points.

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#11]
Suppress the 'Dose Based on field' that shows on this drug prescription page? 

![image](https://github.com/christillman/encounterpro_os/assets/40364841/5521683e-6a71-4c93-90cb-21a6e8eb1b60)

The page can be accessed from various points in the system.

For instance:

From the 'Current Medications' page seen below, click on  the 'Add Meds' button located on the right side of the page.
![image](https://github.com/christillman/encounterpro_os/assets/40364841/551652cb-06dc-4060-b590-026233bc6ac0)

Pick a drug from the 'Select prescription(s) page that is shown next
![image](https://github.com/christillman/encounterpro_os/assets/40364841/ad86574c-7255-49e7-b519-12b1e4f8140d)

I picked the drug name 'oxymetazoline'. The page 'Oxymetazoline'  on which oxymetazoline populates on includes a 'Dose Based On' field, located on the upper right side of the page. See below:
![image](https://github.com/christillman/encounterpro_os/assets/40364841/b0337c81-359c-4e94-8802-85c2dcd8a8fe)

That is the field that I would like suppressed. See below
![image](https://github.com/christillman/encounterpro_os/assets/40364841/5afc9fc7-bb7f-4090-a97b-a2c607e116ce)

This page is linked to the 'Current Meds' service which also displays the current medications page. It can be configured to appear in multiple locations throughout the application as seen below:
![image](https://github.com/christillman/encounterpro_os/assets/40364841/88f2b1ae-85a0-42cc-a29c-abf3f4afb286)

**Comment by christillman** [comment]
We had hidden Dose Based On in one window previously.

// Hide Dose Based on widgets for this release, will add back in later when administrations are available
// CDT 2020-03-29
st_dosebase.Visible = False
uo_drug_administration.Visible = False
st_mult_display.Visible = False

There are 3 other windows which display this, they will be hidden for 7.2.1.2 release.

**Comment by christillman** [comment]
The Current Meds service displays w_svc_drug_treatment_edit. But the Add Drug button actually ends up displaying w_drug_admin_edit. It looks almost the same, but has a button along the bottom for Manual Edit. And there is also a somewhat similar window for Office Drugs, w_office_drug_treatment. Finally w_drug_treatment is the window for choosing prescriptions which we did quite a bit of work on in 202, adding awareness of formulations and Route of Administration. At some point we may want to figure out what needs to be where on each of these, but currently I just hid the Dose Based on part for all of them.

**Comment by christillman** [comment]
Hi Ciru, please check this one in release 7.2.1.2. Let me know if further work is needed.

**Comment by MCIR** [comment]
Actual issue raised here has been fixed. Further discussion on this issue has been raised on issue #20
