### ISSUE TITLE
Ingredients on medications with multiple ingredients are being fitted on select prescription drug(s) page by removing first or last few letters from the ingredient names

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#13]
Hi Chris, 
I noticed that the 'Select prescription drug(s) page' is fitting drugs with multiple ingredients into the available screen space by removing the first or last letters from some ingredients; see below: 
image.png

It is understandable (and I remember we had a discussion about this) that drugs containing multiple ingredients cannot be fitted into the available screen space hence the need to truncate them. 
 
What I am not sure about though, is if removing the first letters of some ingredients was intentional or just a system issue. 

For instance:
**bromhexin.../...uaifenesi.../ ......erbutaline**

Is it possible to fit generic ingredients into the available screen space by fitting whole drug names into the allowed space and leaving off those that will not fit? 

For instance, currently, the medication containing **bromhexine /guaifenesin / terbutaline** is being shown as seen below:

**bromhexin.../...uaifenesi.../ ......erbutaline**

Could we revise this and show whole ingredient names that can be fitted in the available screen space, but allow the user to hover the mouse over the name to view the complete list? For example:  
**bromhexine / guaifenesin /.........**

I think it is safer to display a correct whole ingredient than all ingredients but with missing letters. 

The issue with removing first letters from some ingredients is, some ingredients have very similar names and removing the first few letters from an ingredient will suggest a different ingredient. 
For instance in the case of **pseudoephedrine** and **ephedrine**, if a medication contains the ingredients '**pseudoephedrine/ bromhexine/paracetamol'** but it was truncated to fit the available screen space by removing the first few letters of all its ingredients, it could be shown as:  
**..ephedrine / ..romhexine / ...aracetamol** 

**ephedrine and pseudoephedrine** are two different ingredients so, it is very likely the user will assume the medication contains **ephedrine** not **pseudoephedrine.**

**Comment by christillman** [comment]
Do you have a screen shot? The only truncation code I'm finding is when the generic_name is over 500 characters or common_name is over 80, and that adds ... only at the end. That also wouldn't be different for different screen sizes, the drug shows fine on my (huge) screen.

**Comment by christillman** [comment]
Data fix, also see #74
