### ISSUE TITLE
RTF Scripts display in small text

### ISSUE THREAD

**Issue by christillman** [christillman/encounterpro_os#15]
### Contact Details

toff.tillman@gmail.com

### What happened?

I have been working a lot on improving RTF scripts display because viewing patient notes and summaries is one of the most important aspects of any EMR.

Since the first day physicians and nurses began using the application, a common consistent complaint I am receiving is their current display of their RTF scripts.  Their current  RTF display page  is as seen below.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/5660c39d-0f64-4f6f-82e3-f92d14b3c390)
I am not sure why the page is so small. See mine below:
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/b4e93993-0cd0-45bb-85dd-17c2985850c5)

Is there a way to at least make the page fill the screen a bit more?

The second thing is
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/49bfa151-1c0a-4928-8872-16e3c6bdf305)
The bar at the bottom of the page has buttons 'Print', 'Edit', ;View', and 'Send To...'

What are they coded or configured to do when selected?

One of the things I noticed the physicians want to do is to 'Edit' the document. They want to edit the document, save and print and hand it to the patient .

When I select the 'Edit' button, it first opens a cmd window as seen below. Maybe because I don't have Microsoft word... (it expired).
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/a5089f8d-90be-4d19-b781-45b07da6b480)

### How did it happen?

1. Open the app, log in
2. Select a patient
3. Click on the patient name, select Pick a Report
4. Select a report
5. Choose Preview Report

### Expectations

The report should open in "large" mode so the text is readable.
The Edit button should work.

### Urgency and Importance

Actually I would consider it the most urgent. The customer personnel use this function frequently, many times a day.

### Version

7.2.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christillman** [comment]
For 7.2.1.2, I made the default view the larger one (non-Print Preview. Not that it's not really obvious that there are multiple pages, if there are.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/6f58cd58-cdae-452a-8556-8470469a95be)
The second page is only visible if I use the mouse wheel to scroll down, or if I notice the tiny scroll bar way over at the right edge:
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/7f422f6d-29cc-4f62-8227-cec52de1ea14)
So that may be why it was set to Page as default, so people realize when there is more than one page.

**Comment by christillman** [comment]
I also fixed the Refresh button. If the control was in Page mode as we have now set the default, it generated the letter with strange looking symbols.
![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/14aaaf93-2049-4c6a-8ec7-c57ae6f1a800)
It also left the header in place when refreshing, so the header got duplicated.

![unnamed](https://github.com/christillman/encounterpro_os/assets/25717203/e8c53d4b-6834-4f4a-92e0-91e787b7d659)

So I fixed those issues with the Refresh button by aloways setting the control to Normal mode before refreshing, and then clearing the Header text as well as the Detail text.

**Comment by christillman** [comment]
Finally, on the Edit button. It also didn't work for me. The first problem was that it didn't create the folder hierarchy necessary for saving the tempfile. I fixed that, it will now create it in %TEMP%\Epro. Next it didn't have a valid program to open .doc files. When I tried to open the Powerbuilder-generated .doc with OpenOffice Writer, it failed ... couldn't interpret it. It also seems Microsoft Word doesn't recognize it on the client machines. So I will add the free TextMaker app to the EncounterPro installer. With that installed, the document opens for editing.

**Comment by christillman** [comment]
Hi Ciru, please check this one in release 7.2.1.2. Let me know if further work is needed.

**Comment by MCIR** [comment]
The display below is shown when user selects the sigma button, on the right side of each listed encounter. 

![WhatsApp Image 2023-09-05 at 15 10 38](https://github.com/christillman/encounterpro_os/assets/40364841/0e292e99-8ca5-46bc-a624-7981b413c179)


While the display has changed, from its previous view (page size is larger), the font is now too small and not optimal to view patient notes.

![WhatsApp Image 2023-09-05 at 14 55 44](https://github.com/christillman/encounterpro_os/assets/40364841/0d83d3e2-b613-47d1-a0ef-519fc6497018)

Another view of RTF pages is seen when user selects the page button located at the bottom of the 'chart' page, right above the 'Clinic Notes' tab. See image of button below: 
![WhatsApp Image 2023-09-05 at 15 14 05](https://github.com/christillman/encounterpro_os/assets/40364841/8168a1ea-1761-466e-acbe-f40e4bde9f27)

The page size appears to be smaller and the script exceeds the page boundaries. 

![WhatsApp Image 2023-09-05 at 15 18 40](https://github.com/christillman/encounterpro_os/assets/40364841/d2b67001-eae0-4bbd-bff0-062d1b3cb349)

**Comment by christillman** [comment]
7.2.1.4 will fix the page boundaries problem. Unfortunately, somehow, the font color settings are no longer being applied as specified in the display script. I'm puzzled why it happened, but haven't yet been able to find a way to make it work again.
