### ISSUE TITLE
When creating a new patient, selecting finished shows a message "The id document type is required’

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#23]
From this window used to create a new patient record
![image](https://github.com/christillman/encounterpro_os/assets/40364841/428bb3f6-65b1-41e9-b266-abfbc1323005)
Unable to proceed past this window. When I select ‘Finish’ I get the error message “The id document type is required’. Unable to proceed past this error message to create a new patient record. 

![image](https://github.com/christillman/encounterpro_os/assets/40364841/07c7e9af-785f-4c0a-8976-82fde5ff1615)
 

This message is applicable to a different page.

**Comment by christillman** [comment]
I logged into your database which is at version 7.2.1.1 currently on my machine. I got the Document Id showing.

![image](https://github.com/christillman/encounterpro_os/assets/25717203/c7154cf3-6952-4b68-b989-022881548f9c)

Let me see how SSN could be showing. First to check is the country in c_Office.

select country from c_Office

My response is
ug

**Comment by christillman** [comment]
The document_id validation is not applicable when the SSN field is showing. I have fixed the validation to not require id document type and document id unless the id document type and document id fields are visible. (in 7.2.1.3).

**Comment by christillman** [comment]
I'm not setting the new patient window fields according to the country in c_Office. Instead I am setting it according to the registry locale in HKEY_CURRENT_USER\Control Panel\International\LocaleName. This is controlled from the Regional Settings Control Panel. In Windows 11:

![image](https://github.com/christillman/encounterpro_os/assets/25717203/ea975499-d36c-4264-87c9-3e57f204f459)

**Comment by christillman** [comment]
(copied from https://github.com/christillman/encounterpro_os/issues/9)
Changed the Regional settings in Control Panel to Uganda. It resolved the issue. I am able to create new patient record with no problems and title casing appropriately applied to all new patient fields. This change made changes to registry settings in HKEY_CURRENT_USER\Control Panel\International\LocaleName
![image](https://github.com/christillman/encounterpro_os/assets/25717203/e019b01f-cbda-4f76-85a9-ca2de956357e)

**Comment by christillman** [comment]
Cool, I have updated the validation settings also in 7.2.1.3. I'll close this one now, because there is no need to test the U.S. validation settings ... not used at the moment.
