### ISSUE TITLE
Edit Prescription Drug button appears to be inactivated. 

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#26]
'Edit Prescription Drug' button appears inactivated. 

User should be able to access the edit prescription drug page by select the capsule icon located on the left side of the drug name. 

![image](https://github.com/christillman/encounterpro_os/assets/40364841/d3b867c0-cb05-48e9-8d31-397bd5296e4f)

The page can be accessed by selecting the capsule icon shown below

![image](https://github.com/christillman/encounterpro_os/assets/40364841/33c3908d-1220-44ce-bbc8-dabeb5b0172f)
 
or by selecting the 'Meds' button located in the top center section of patient chart, seen below

![image](https://github.com/christillman/encounterpro_os/assets/40364841/fc973ea7-a1a2-4eae-a189-f4f2d254775a)

which opens the page shown below:

![image](https://github.com/christillman/encounterpro_os/assets/40364841/ee265c4b-b0a0-413e-9c82-9d34e7e8e437)

From this page, selecting the capsule icon located on the left side of the drug name should open the 'Edit Prescription' page.

**Comment by christillman** [comment]
Are you working in 7.2.1.3? That is one of the advantages of using the Bug template, it requires that you select which version you observed the problem in.

I verified this was working in my testing of 7.2.1.3.

**Comment by christillman** [comment]
Sweet, thanks
