### ISSUE TITLE
Users unable to make corrections to patient sex, usually done through the 'Sex' field

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#27]
Users (including super users) are unable to correct patient's sex. 

Correcting the patient sex should be possible for certain users, through the 'Sex' field, located on the patient demographics page. This  page can be accessed by searching for and selecting the patient's medical record or by selecting 'Edit patient data' button that can be found in multiple areas in the patient's chart. Though it is currently possible for the user to revise the sex displayed from 'Male' to 'Female' or from 'Female' to 'Male' by toggling between the two options, any changes made are not saved or updated into the record. 
![image](https://github.com/christillman/encounterpro_os/assets/40364841/39f64e79-a3c1-491f-9e21-8b0102642530)

**Comment by christillman** [comment]
I fixed these two patient sex issues in the next release. Let me know if I should build it urgently.
