### ISSUE TITLE
Users attempting to make corrections to patient sex field have to toggle between 4 options instead of 2

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#28]
On patient demographic page, revise the sex field to display the complete sex name  'Female' or 'Male', instead of the abbreviations 'M' or 'F'. 

Related to this, currently, when the user attempts to revise the display, they have to toggle between 3 options. 

For example, if the sex assigned at registration was 'Female' the sex field will be showing the letter 'F'. When the user attempts to make changes by toggling between the possible options, it will first change to the word 'Female', then 'Male'. 

If the patient had been assigned the sex 'Male' at registration, the sex field will be showing the letter 'M'. Then when user attempts to make changes by toggling between the possible options, it will first change to the word 'Male', then 'Female'. 

See below. 
![image](https://github.com/christillman/encounterpro_os/assets/40364841/47a516f9-7c58-4568-a3dd-a9357b059788)

![image](https://github.com/christillman/encounterpro_os/assets/40364841/b4388633-031f-4828-b608-11887526ef61)

![image](https://github.com/christillman/encounterpro_os/assets/40364841/fab7c2e8-7c8f-487f-a386-60e99bcd88fc)

![image](https://github.com/christillman/encounterpro_os/assets/40364841/201398f8-7b5a-4679-a44c-f249ea3b031e)

Revert the field to the legacy application setting which was, to have the field display either 'Female' or 'Male' options, as well as having users only toggle between those two options.

**Comment by christillman** [comment]
I fixed these two patient sex issues in the next release. Let me know if I should build it urgently.
