### ISSUE TITLE
Users not able to make changes to their personal shortlists unless they've been given privileges to 'edit common shortlists'

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#30]
Users in 7.2.1.1 are unable to add/remove from their personal short lists unless they've been assigned the permission to 'edit common shortlists'. It should be possible for users to have the ability to make changes to add/remove from their personal short list despite not having permission to edit (add/remove) common short lists. 

I think this is linked to issue #21

**Comment by christillman** [comment]
I think you're right, it was related to #21. Can you verify it doesn't require permission for a regular user now? I recall testing it in August.

**Comment by christillman** [comment]
Closing as #38 covers the same territory and has great detailed discussion.
