### ISSUE TITLE
Utilities 1.0.5 not working on some computers

### ISSUE THREAD

**Issue by christillman** [christillman/encounterpro_os#32]
### Contact Details

toff.tillman@gmail.com

### What happened?

On new installations, when Utilities 1.0.5 is installed, the connection to the utilities might not work on some computers. This happens on Ciru's computer.

Then when Epro is started up and detects the need for a database upgrade, Utilities is used to read the upgrade file. When Utilitities isn't working, that fails and the application is not upgradeable.

Workaround is to install Utilities 1.0.1 which seems to work on all computers.

Because 1.0.1 uses obsolete libraries which could be removed from Windows at any time, it must be replaced. It can't be rebuilt because the libraries are no longer available. Utilities 1.0.5 is the latest attempt to rebuild Utilities with current libraries, but it doesn't work on some machines.

The path forward is to either build a version of Utilities which works on all machines, or replace the Utilities functions with something equivalent.

The problematic call to Utilities for upgrading is in u_event_log.file_read 
   common_thread.eprolibnet4.FileToBytes(ps_file)

### How did it happen?

Open a newly installed version of EncounterPro (database not yet upgraded) on a computer where Utilities 1.0.5 does not work. 

The app connects to the database and determines it is an older version than the application needs.

The upgrade dialog is shown. But when a schema file is located, when the file is read, it fails because of unavailability of Utilities. 

The following series of dialogs is seen.

![1940fa2d-5fb0-4198-9dba-00dae79cd77d](https://github.com/christillman/encounterpro_os/assets/25717203/4d6b76cb-82b0-48e3-a8bd-cbe5972b9d7b)

![cdaa84ad-74f2-49f7-b1e8-01387f0c0b5e](https://github.com/christillman/encounterpro_os/assets/25717203/4db6901d-6425-4cf7-a279-24771962c312)

![e9b8652e-193c-48c2-8256-ff0b4702ad6a](https://github.com/christillman/encounterpro_os/assets/25717203/ca702003-e183-4281-8a8f-c5e63e0ef50d)

![043ada02-d5ec-4c75-a1c6-06d4ff696bf9](https://github.com/christillman/encounterpro_os/assets/25717203/c980d4c8-d685-4207-9e0b-c84467c20437)

![972dd883-f54d-446b-8c75-7f9378c8592c](https://github.com/christillman/encounterpro_os/assets/25717203/8c385695-7f52-46bf-8f96-b793defc49fb)

The upshot is, you can't upgrade unless you having a working version of utilities

### Expectations

The utilities functions are needed and utilities must work.

### Urgency and Importance

An important function is being able to upgrade the application.

### Version

7.2.1.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christillman** [comment]
Built Utilities 1.0.6 from the 1.0.1 source, with the minimal amount of changes to bring it up to the current 4.8 .Net framework. This was reported to still not work on the computers where it is a problem.

Then I replaced the file utilities and encoding/decoding routines from the Utilities package with basic Powerbuilder file and encoding commands which have become available since the Utilities was designed. The plan is make other substitutions for the remaining Utilities functions: image handling, compression, xml transformation, encryption, ftp, program execution, admin user check.

**Comment by MCIR** [comment]
We can now upgrade if utilities are not found
