### ISSUE TITLE
The page used to view clinic notes is not automatically selecting the latest encounter when it opens.

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#34]
When a user navigates to the patient chart, the initial page they encounter is this page shown below, which I will refer to as the main SOAP page. 
![image](https://github.com/christillman/encounterpro_os/assets/40364841/60daa523-3007-4fcf-a55c-32b92f9ed645)

 
When the page opens, it will automatically default to the most recent encounter indicated by the black box encircling the encounter at the top. 
![image](https://github.com/christillman/encounterpro_os/assets/40364841/50d649cf-db7d-490a-8a54-5ce0175d52ca)

 

The patient data seen in the large square space on the right is from the highlighted encounter on the left. Therefore, when this main SOAP chart page is initially loaded, the first thing the user will encounter in the large square space on the right is patient data from the currently selected encounter, which is the most recent one. This way, the system will automatically show the user, the patient data from the latest encounter."
![image](https://github.com/christillman/encounterpro_os/assets/40364841/25808115-dab4-4c6e-9864-925ad917e45b)

 

If they want to see information from previous encounters, they need to select the encounter bar which will be below the most recent encounter. 

To view patient data from prior encounters, they must select the encounter bars corresponding to the dates of their interest, listed below the most current encounter. 
 
![image](https://github.com/christillman/encounterpro_os/assets/40364841/5196fd2c-25cd-4b34-95a8-a5fffdeeb0c2)

This configuration is optimal since it allows the user to immediately view patient data associated with the most recent encounter upon opening the page.
I'd like to replicate this functionality on this 'Clinic Notes' tab, but I'm unsure of how to do it. 
 
![image](https://github.com/christillman/encounterpro_os/assets/40364841/0e0f1a42-3824-433b-bbf7-a51090459c3e)

Currently, when a user wants to access the ‘Clinic Notes’ page by clicking on the ‘Clinic Notes’ tab, the page opens, but it remains empty because no encounter is preselected, as shown below.
![image](https://github.com/christillman/encounterpro_os/assets/40364841/c7f6094d-b97f-4eca-b612-1f94911d3dad)

The user needs to manually select the most recent encounter to display the corresponding patient data in the empty space on the right. See below:
 
![image](https://github.com/christillman/encounterpro_os/assets/40364841/411b16bf-2b6f-40a0-bef9-ea7467d92476)

Can the configuration under this 'Clinic Notes' page be adjusted to match configuration in the main SOAP chart page, where the most recent encounter is selected, and it displays data from that encounter in the RTF script

**Comment by christillman** [comment]
I could make it so the script runs to populate the document from the most recent encounter, when the user clicks on the clinic notes tab.

Just to check, is that similar to what other tabs do? Do they always show the most recent encounter when clicked on? Or is the selection of encounter "sticky", so that if you select a previous encounter and then another tab, it shows the previous encounter's information on the most recently clicked tab?

And just noting that because the script rebuilds the text every time, there will be a short delay after the user clicks on the Clinic Notes tab, and also after they click on another Encounter as it rebuilds.

**Comment by MCIR** [comment]
Hi Chris, 

Just to check, is that like what other tabs do? Do they always show the most recent encounter when clicked on? Or is the selection of encounter "sticky", so that if you select a previous encounter and then another tab, it shows the previous encounter's information on the most recently clicked tab?

Patient data to the selected encounter on the primary page. 

 

The patient’s chart can display different types of pages and it is possible to add/remove pages to the patient’s chart page. 

 

In pediatrics specialty, the ‘Assessment’ page is the landing page after user selects the ‘View Chart’ button.  

 

When the page opens, it defaults to showing patient data from the patient’s most recent appointment, so the most recent encounter is selected as seen below. 

 



 

The tabs at the bottom are what I can refer to as the primary pages, and the top tabs are secondary pages. Each primary page can have several secondary pages represented by the tabs at the top. 



 

The patient data shown on secondary pages will be from the date of the encounter chosen on the primary page. 

 

For example, the screenshot above shows the ‘Assessment’ page as the primary page. The encounter selected on that page is from 08/11/2021. So patient data on ‘Triage Summary’ tab as well as from the ‘Appointment Summary’ tab will be from 08/11/2021. Drug Hx page is a ‘Summary’ page designed to show patient’s entire drug history.  

 

See below the ‘Triage Summary’ page has date selected as 08/11/2021. 



 

At the bottom of the chart page, if we select the second tab from the left named 'Clinic Notes,' we will be viewing another primary page. See below:



 

When the tab is clicked, it presents a different type of page known as an 'observation page' which shows patient data through RTF scripts. 

 

Currently when it is displayed, it does not automatically display patient data from the most recent encounter which is why it appears blank. 

 

I initially expected that when this page is first opened, it would automatically show patient data from the most recent encounter, which, in this case would be 22/08/2023.

 

Interestingly, when I click the other top tabs ‘Diagnosis & Treatment’ and ‘Clinic Notes’ they do default to the most recent appointment, so I am not sure why this is happening. 

 

Or is the selection of encounter "sticky", so that if you select a previous encounter and then another tab, it shows the previous encounter's information on the most recently clicked tab?

When I change the encounter date on any of the secondary tabs within the ‘Clinic notes’ primary page (‘History & Physical’, ‘Diagnosis & Treatment’ and ‘Consultation Notes’), the change is applied to the other secondary pages within the ‘Clinic Notes’ as well as the primary ‘Chart’ page and its associated secondary tabs including ‘Triage Summary’. In other words, when an encounter date is chosen on one page, it impacts the entire patient chart. I appreciate this behavior because it is working as expected. 

 

Does this answer your question?
