### ISSUE TITLE
Error messages when application disconnects from server

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#39]
Hi Chris, 

https://1drv.ms/v/s!AuBDbs81Gi8WgZQpwyFSvfhqrn-MnQ?e=aerNYk 

The link provided above leads to a brief video demonstrating new behavior I noted, after a period of inactivity on the application.  

During the incident I captured in the video, I was working on the import page but regardless of the specific page the user is on, they will still be shown multiple error messages, requiring them to click ‘OK’ to proceed or exit from the application. These messages take over a minute before showing the user the final conclusion, which is the application has disconnected from the server and they need to login once again.  There are some instances though where error messages begin to pop up even when the application is being actively used. 

The application’s buttons remain functional, as seen in this particular instance, however in other scenarios, clicking the buttons produces no results. 

The video is approximately 2 minutes and 30 seconds, roughly the time it takes to get to the last error message and close the application. I usually just advise users to press CTRL+ALT+Delete to be able to close the program and login again. For physicians pressed for time, 2 minutes to close the application and start afresh can feel like a really long time.

**Comment by christillman** [comment]
I tested this by opening up to a client chart and then stopping the SQL Server service. When I switched back to the application, I was immediately presented with 
![image](https://github.com/christillman/encounterpro_os/assets/25717203/8b2072ad-5dd2-494f-9ff5-1978a625c59a)

After dismissing this, the application was closed but one more alert was shown
![image](https://github.com/christillman/encounterpro_os/assets/25717203/ab82fdb4-f669-46db-b0d7-a5810b85f534)
