### ISSUE TITLE
Bug: Application displaying error message after creating new observation 

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#50]
### What happened?

In version 7.2.1.8. 
An error message is displayed after completing the final step of creating a new observation. Despite the error message, the observation saves successfully and remains searchable.

### How did it happen?

See link below to video illustrating the problem. 
https://1drv.ms/v/s!AuBDbs81Gi8WgZs3QFXmH_uhouMaGg?e=HZKB49

### Expectations

I expected ...no error messages shown after new observation is created. 

### Urgency and Importance

Urgency is moderate at this point. Unclear about the extent of the issue's impact on the configuration process as well as its impact on the documentation process when the observation is incorporated into the assessment.  

### Version

other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christillman** [comment]
Thanks Ciru. This was a rare original 6.2.6 bug.
