### ISSUE TITLE
Track user that created new patient charts

### ISSUE THREAD

**Issue by MCIR** [christillman/encounterpro_os#68]
Currently, it is not possible to track who created patient charts. This applies to new patient charts. It looks like it is possible to track this because the created_by column is showing 'NULL' for all patient charts. Would like to make it possible to track which user created new patient charts and if possible which user merged patient charts.

**Comment by christillman** [comment]
I believe the nulls are being placed because the new_encounter call uses "current_scribe" as the user_id.

```
// Create the new appointment
ll_encounter_id = current_patient.new_encounter(lstr_encounter, &
										current_scribe.user_id, &
										lb_open_encounter)
```
I think the current_scribe should be set to the current_user if scribing is not in use. I'll check to see why that is not occurring.

**Comment by MCIR** [comment]
Okay thank you

**Comment by MCIR** [comment]
Now able to track which user created patient chart.
